### ISSUE TITLE
Can I install this over CleanDebian Jessie?

### ISSUE THREAD

**Issue by hrvstr** [FoxExe/wdmc-gen1-tools#1]
Hi Fox,
I installed your Image "CleanDebian-Jessie.tgz" (28-Nov-2015 20:39). Can I use the "update-debian-dist.sh" script from this repo to update the page file? Will there be a boost in performance? Is there anything else I need to do to keep the system running beside apt-get update & upgrade?

Best regards,
HRVSTR

**Comment by FoxExe** [comment]
This tools for build apps for firmware v04.x
You can use my repo for install Debian with modified "Memory page size = 64kb". But its not increase performance, because need additionaly add support for large pages for Samba and other software.

For normal Debian (With ps=4kb) no need to modify anything - just install/compile as normal.
And yes - "Clean debian" can update via apt to latest version. System have only one modification - Kernel.
